spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://192.168.56.1:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
server:
  port: ${PORT:8080}
jwt:
  secret: ${JWT_SECRET:ChangeThisJWTSecret!_YourSecretIsNotSafeUntilYouReplaceMe_1234567890abcdef}